name: Salesforce CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: karamchandanid/sfdc-credentials-auth@v2
        id: sfdc_auth
        with:
          sfdc_client_id: ${{ secrets.SFDC_CLIENT_ID }}
          sfdc_client_secret: ${{ secrets.SFDC_CLIENT_SECRET }}
          user_name: ${{ secrets.SFDC_DEV_USERNAME }}
          password: ${{ secrets.SFDC_DEV_PASSWORD }}
          login_url: https://cognizant62.my.salesforce.com/
      
      - name: sfdc_auth_details
        run: |
          # Validating access_token if null then terminate the process
          if [[ -z ${{ steps.sfdc_auth.outputs.access_token }} ]] || [[ ${{ steps.sfdc_auth.outputs.access_token }} == "null" ]];
          then 
            echo "----------------------------------"
            echo "Error in salesforce authentication"
            echo "----------------------------------"
            echo "$error ${{ steps.sfdc_auth.outputs.error }} : ${{ steps.sfdc_auth.outputs.error_description }}"
            echo ""
            exit 1;
          fi
          # on success proceed following
          echo ${{ steps.sfdc_auth.outputs.instance_url }}
          echo ${{ steps.sfdc_auth.outputs.id }}
          echo ${{ steps.sfdc_auth.outputs.access_token }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Salesforce CLI
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      #- name: Authenticate with Salesforce
      #  run: |
      #    echo ${{ secrets.SALESFORCE_AUTH_URL }} > auth-url.txt
      #    sfdx force:auth:sfdxurl:store -f auth-url.txt -a dev-org

      - name: Install dependencies
        run: npm install

      - name: Run Apex tests
        run: sfdx force:apex:test:run -l RunAllTestsInOrg -w 10

      - name: Deploy to Salesforce
        run: sfdx force:source:deploy -p force-app -u dev-org -w 10
